---
title: koa优雅抛出错误
date: 2021-06-04 09:01:02
permalink: /pages/0621f6/
categories: 
  - 前端
  - Node文章
tags: 
  - koa
---
> 前面的文章《ajv参数校验》提到要为所有接口做参数校验，校验未通过需要返回相同的错误，每次都要在校验之后判断是否错误，返回给客户端。为什么不直接抛出错误统一处理呢？

```js
if(error) {
      ctx.status = 400;
      ctx.body = {
        msg: '数据校验失败'
      }
```

## Koa中自带的错误处理

常见抛出异常和错误类型：

● 代码语法不规范造成的JS报错异常

● 程序运行中发生的一些未知异常

● HTTP错误

● 自定义的业务逻辑错误

 koa中，通过 `ctx.throw( 状态码 )` 来抛出异常， 也可以携带自己想提示错误信息。

```js
ctx.throw(400, '参数错误')

/* .catch( error => {
  consloe.log({error.status, error.message})
  // 400 参数错误
})*/
```

## 自定义错误处理中间件

但这样不符合Restful API标准，我们应尽量使用json格式返回信息

所以我们可以自己写一个中间件，在 `app.use(router())` 前添加中间件用 `next().catch()` 对错误进行捕获。

`src/index.js`

```js
const httpError = require('./middleware/httpError')

/* http错误处理中间件 */
app.use(httpError())

app.use(router())
```

`src/middleware/httpError.js`

```js
const httpError = function () {
  return async function (ctx, next) {
    return next().catch( error => {
      const errorCode = error.status || error.statusCode;
      // 不是通过ctx.throw()抛出的错误
      if(errorCode === undefined) {
        // 可以把这个错误写进错误日志
        console.error(error);
      }
      ctx.status = errorCode || 500;
      // 自定义状态码对应的消息
      const ERROR_MSG = {
       '400': '400 Bad Request：服务器不理解客户端的请求，未做任何处理。',
       '401': '401 Unauthorized：用户未提供身份验证凭据，或者没有通过身份验证。',
       '403': '403 Forbidden：用户通过了身份验证，但是不具有访问资源所需的权限。',
       '404': '404 Not Found：所请求的资源不存在，或不可用。',
       '405': '405 Method Not Allowed：用户已经通过身份验证，但是所用的 HTTP 方法不在他的权限之内。',
       '410': '410 Gone：所请求的资源已从这个地址转移，不再可用。',
       '415': '415 Unsupported Media Type：客户端要求的返回格式不支持。比如，API 只能返回 JSON 格式，但是客户端要求返回 XML 格式。',
       '422': '422 Unprocessable Entity ：客户端上传的附件无法处理，导致请求失败。',
       '429': '429 Too Many Requests：客户端的请求次数超过限额。',
       '500': '500 Internal Server Error：客户端请求有效，服务器处理时发生了意外。',
       '503': '503 Service Unavailable：服务器无法处理请求，一般用于网站维护状态。'
      }
      ctx.body = {
        code: ctx.status,
        msg: ERROR_MSG[`${ctx.status}`]
      }
    })
  }
}

module.exports = httpError
```

### 对比

**使用前**

```js
const { uid } = ctx.query;
if (!uid) {
  ctx.status = 400;
  ctx.body = {
    code: 400,
    msg: '参数错误'
  }
  return
}
```

**使用后**

```js
const { uid } = ctx.query;
if (!uid) ctx.throw(400);
```

**使用前**

```js
// ajv 参数校验
// SCHEMA 写好的数据规则
const { body } = ctx.request;
const error = validate(SCHEMA, body);
if(error){
    ctx.status = 400
    ctx.body = {
        code: 400,
        msg: '参数错误'
    }
    return
}
```

**使用后**

```js
const { body } = ctx.request;
const error = validate(SCHEMA, body);
if(error) ctx.throw(400);
```

### 2021-6-19更新

后续的使用中发现这个功能没必要，统一返回数据格式 `ctx.fail( 'xxxx', code )` 的方法更好的解决返回错误，还是把这个中间件删了吧。